# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 055df2e4736e70a7be614ff7165c5b6ae764aa1ec4ca1b9e764a977eedab5b85c355aa1c18a5926ab2fbece6e8f7b704208ae39cbc14e4e39d60709d52057527

test:
  secret_key_base: 5e429e7a15afa19a36f170ff92e4aaf9a48dd8554b0927b3d4ae7e3fe4b8444185bd2a635a2cacb2e9d1eb416ced61c2dc4e2366dc10077a9271c1f308a7d46e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 270333fd4d22be56124dcb988637e23fd89c3518aba5141ab7b53dd01a88f3edc587cc28611bffc5d82fc4256ef1890adae03e95b0d3f7e7edf3186d28cce4a9
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
